// client_react/src/auth/Register.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthService } from '../auth/AuthAPI';
import { validateEmail, validatePassword } from '../services/regex';
import './register.css';

const Register = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [firstName, setFirstName] = useState('');
  const [name, setName] = useState('');
  const [error, setError] = useState({});
  const navigate = useNavigate();
  const { register } = useAuthService();

  const handleRegister = (e) => {
    e.preventDefault();
    let isValid = true;
    let errors = {};

    if (!validateEmail(email)) {
      errors.email = 'Format d\'email invalide';
      setEmail('');
      isValid = false;
    }

    if (!validatePassword(password)) {
      errors.password = 'Le mot de passe doit contenir au moins 12 caractères, dont une majuscule, une minuscule, un chiffre et un caractère spécial';
      setPassword('');
      setConfirmPassword('');
      isValid = false;
    }

    if (password !== confirmPassword) {
      errors.confirmPassword = 'Les mots de passe ne correspondent pas';
      setConfirmPassword('');
      isValid = false;
    }

    setError(errors);

    if (isValid) {
      register(email, password, firstName, name).then(() => {
        navigate('/categorie');
      });
    }
  };

  return (
    <div className="register-container">
      <div className="register-form-container">
        <h2>Inscription</h2>
        <form onSubmit={handleRegister} className="register-form">
          <div className="input-group">
            <label>Prenom</label>
            <input type="text" value={firstName} onChange={(e) => setFirstName(e.target.value)} />
            {error.firstName && <div className="error-message">{error.firstName}</div>}
          </div>
          <div className="input-group">
            <label>Nom</label>
            <input type="text" value={name} onChange={(e) => setName(e.target.value)} />
            {error.name && <div className="error-message">{error.name}</div>}
          </div>
          <div className="input-group">
            <label>email</label>
            <input type="text" value={email} onChange={(e) => setEmail(e.target.value)} />
            {error.email && <div className="error-message">{error.email}</div>}
          </div>
          <div className="input-group">
            <label>Mot de passe</label>
            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
            {error.password && <div className="error-message">{error.password}</div>}
          </div>
          <div className="input-group">
            <label>Confirmer le mot de passe</label>
            <input type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} />
            {error.confirmPassword && <div className="error-message">{error.confirmPassword}</div>}
          </div>
          <button type="submit" className="register-button">Register</button>
        </form>
      </div>
    </div>
  );
};

export default Register;

// client_angular/src/app/auth/register/register.component.ts
import { Component } from '@angular/core';
import { FormGroup, FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';
import { passwordMatchValidator } from '../../validator/password.validator';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [ReactiveFormsModule, HttpClientModule, CommonModule],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent {
  registerForm: FormGroup;
  error: string | null = null;

  constructor(private authService: AuthService, private formBuilder: FormBuilder, private router: Router) {
    this.registerForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', [Validators.required]],
      name: ['', Validators.required],
      firstName: ['', Validators.required],
    }, { validators: passwordMatchValidator });
    
  }

  onRegister(): void {
    if (this.registerForm.invalid) {
      this.error = 'Le formulaire n\'est pas valide !';
      return;
    }
  
    const { email, password, name, firstName } = this.registerForm.value;
    this.authService.register(email, password, name, firstName).subscribe((success: boolean) => {
      if (success) {
        this.router.navigate(['/categorie']);
      } else {
        this.error = 'L\'inscription a échoué !';
      }
    });
  }
  
}

<div class="register-container">
  <form [formGroup]="registerForm" (ngSubmit)="onRegister()">
    <div>
      <label for="email">Email :</label>
      <input type="email" formControlName="email" id="email">
      <div *ngIf="registerForm.get('email')?.errors?.['required'] && registerForm.get('email')?.touched">
        L'email est requis.
      </div>
      <div *ngIf="registerForm.get('email')?.errors?.['email'] && registerForm.get('email')?.touched">
        Veuillez entrer une adresse email valide.
      </div>
    </div>

    <div>
      <label for="name">Nom :</label>
      <input type="text" formControlName="name" id="name">
      <div *ngIf="registerForm.get('name')?.errors?.['required'] && registerForm.get('name')?.touched">
        Le nom est requis.
      </div>
    </div>

    <div>
      <label for="firstName">Prénom :</label>
      <input type="text" formControlName="firstName" id="firstName">
      <div *ngIf="registerForm.get('firstName')?.errors?.['required'] && registerForm.get('firstName')?.touched">
        Le prénom est requis.
      </div>
    </div>

    <div>
      <label for="password">Mot de passe :</label>
      <input type="password" formControlName="password" id="password">
      <div *ngIf="registerForm.get('password')?.errors?.['required'] && registerForm.get('password')?.touched">
        Le mot de passe est requis.
      </div>
      <div *ngIf="registerForm.get('password')?.errors?.['minlength'] && registerForm.get('password')?.touched">
        Le mot de passe doit comporter au moins 6 caractères.
      </div>
    </div>

    <div>
      <label for="confirmPassword">Confirmez le mot de passe :</label>
      <input type="password" formControlName="confirmPassword" id="confirmPassword">
      <div *ngIf="registerForm.errors?.['passwordMismatch'] && registerForm.get('confirmPassword')?.touched">
        Les mots de passe ne correspondent pas.
      </div>
    </div>

    <button type="submit" [disabled]="registerForm.invalid">S'inscrire</button>

    <div *ngIf="error" class="error">
      {{ error }}
    </div>
  </form>
</div>
