// client_angular/src/app/panier/panier.component.ts
import { Component, OnInit } from '@angular/core';
import { PanierService } from '../services/panier.service';
import { ProduitService } from '../services/produit.service';
import { CommonModule } from '@angular/common';
import { get } from 'http';

@Component({
  selector: 'app-panier',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './panier.component.html',
  styleUrl: './panier.component.scss'
})


export class PanierComponent implements OnInit {
  produits: any[] = [];
  quantites: { [id_produit: string]: number } = {};
  label : { [id_produit: string]: string } = {};
  prix : { [id_produit: string]: number } = {};
  url : { [id_produit: string]: string } = {};
  total : number = 0;

  constructor(private panierService: PanierService, private produitService: ProduitService ) {}
  

  ngOnInit(): void {
    this.chargerPanier();
  }

  chargerPanier(): void {
    console.log("test")
    this.panierService.obtenirPanier().subscribe({
      next: (panier) => {
        console.log('Panier', panier);
        this.produits = panier;
        panier.forEach(produit => {
          this.quantites[produit.id_produit] = produit.quantite;
          this.getProduit(produit);
        });
        console.log('produits' , this.produits);
      },
      error: (error) => {
        console.error('Erreur lors de la récupération du panier', error);
      }
    });
  }

  

  ajouterAuPanier(produit: any): void {
    if (!this.quantites[produit.id_produit]) {
      this.quantites[produit.id_produit] = 0;
    }
    this.quantites[produit.id_produit]++;

    this.panierService.ajouterAuPanier(produit);
    this.calculerTotal();
  }

  enleverDuPanier(produit: any): void {
    if (!this.quantites[produit.id_produit]) {
      this.quantites[produit.id_produit] = 0;
    }
    this.quantites[produit.id_produit]--;
    if(this.quantites[produit.id_produit] <= 0) {
      this.produits = this.produits.filter(p => p.id_produit !== produit.id_produit);
    }

    this.panierService.enleverDuPanier(produit);
    this.calculerTotal();
  }

  enleverDuPanierProduit(produit: any): void {
    this.produits = this.produits.filter(p => p.id_produit !== produit.id_produit);
    this.panierService.removeFromCart(produit.id_produit);
    this.calculerTotal();
  }

  getProduit(produit : any): any {
    this.produitService.getProduit(produit.id_produit).subscribe(
      (data) => {
        this.label[produit.id_produit] = data.label;
        this.prix[produit.id_produit] = data.prix;
        this.url[produit.id_produit] = data.url;
        this.calculerTotal();
      }
    );
  }

  calculerTotal(): void {
    this.total = 0;
    this.produits.forEach(produit => {
      if (this.prix[produit.id_produit] && this.quantites[produit.id_produit]) {
        this.total += this.prix[produit.id_produit] * this.quantites[produit.id_produit];
      }
    });
  }

  viderPanier(): void {
    this.panierService.viderPanier().subscribe({
      next: () => {
       this.chargerPanier();
      },
      error: (error: any) => {
        console.error('Erreur lors de la suppression du panier', error);
      }
    });
  }
  
}

<div class="panier-list">
    <h2>Panier</h2>
    <div class="panier-container">
        <div *ngFor="let produit of produits" class="category-card">
            <div class="category-content">
                <img *ngIf="url[produit.id_produit]" [src]="url[produit.id_produit]" alt="{{label[produit.id_produit]}}">
                <div>{{ label[produit.id_produit] }}</div>
                <div>{{ prix[produit.id_produit] | currency }}</div>
                <div><button (click)="ajouterAuPanier(produit)">+</button> {{ quantites[produit.id_produit] }} <button (click)="enleverDuPanier(produit)">-</button>  </div>
                <button (click)="enleverDuPanierProduit(produit)">Enlever du panier</button>
            </div>
        </div>
    </div>
    <div class="total">
        <div>Nombre de produits: {{ produits.length }}</div>
        <div>Total: {{ total | currency }}</div>
        <div></div>
        <button (click)="viderPanier()">Vider le panier</button>
    </div>
</div>

// client_react/src/panier/Panier.js
import React, { useEffect, useState } from "react";
import { addProduitToPanier, deleteProduitFromPanier, getUserPanier, deleteEntieryProduitFromPanier, viderPanierUtilisateur, getPanierWithPrice } from './PanierAPI';
import "./Panier.css"; // Assurez-vous que le fichier CSS est bien lié

const Panier = () => {
    const [panier, setPanier] = useState([]);
    const [total, setTotal] = useState(0);

    useEffect(() => {
        chargerPanier();
    }, []);

    const chargerPanier = async () => {
        try {
            const items = await getPanierWithPrice();
            setPanier(items);
            calculerTotal(items);
            console.log(items);
        } catch (error) {
            console.error('Erreur lors de la récupération du panier', error);
        }
    };

    const ajouterAuPanier = async (id_produit) => {
        try {
            await addProduitToPanier(id_produit);
            chargerPanier();
        } catch (error) {
            console.error('Erreur lors de l\'ajout du produit au panier', error);
        }
    };

    const enleverDuPanier = async (id_produit) => {
        try {
            await deleteProduitFromPanier(id_produit);
            chargerPanier();
        } catch (error) {
            console.error('Erreur lors de la suppression du produit du panier', error);
        }
    };

    const supprimerProduitPanier = async (id_produit) => {
        try {
            await deleteEntieryProduitFromPanier(id_produit);
            chargerPanier();
        } catch (error) {
            console.error('Erreur lors de la suppression du produit du panier', error);
        }
    }

    const calculerTotal = (items) => {
        const totalCalcule = items.reduce((acc, item) => acc + item.produit.prix * item.quantite, 0);
        setTotal(totalCalcule);
    };

    const viderPanier = async () => {
        try {
            await viderPanierUtilisateur();
            chargerPanier();
        } catch (error) {
            console.error('Erreur lors de la suppression du panier', error);
        }
    }

    return (
        <div className="panier-list">
            <h2>Panier</h2>
            <div className="panier-container">
                {panier && panier.map(item => (
                    <div key={item.produit.id_produit} className="panier-card"> {/* Changez 'panier.id_produit' par 'item.produit.id_produit' */}
                        <div className="panier-content">
                            <img src={item.produit.url} alt={item.produit.label} />
                            <div>{item.produit.label}</div>
                            <div>{item.produit.prix} €</div>
                            <div>
                                <button onClick={() => ajouterAuPanier(item.produit.id_produit)}>+</button>
                                {item.quantite} {/* Modifier 'produit.quantite' par 'item.quantite' */}
                                <button onClick={() => enleverDuPanier(item.produit.id_produit)}>-</button>
                            </div>
                            <button onClick={() => supprimerProduitPanier(item.produit.id_produit)}>
                                Enlever du panier
                            </button>
                        </div>
                    </div>
                ))}
            </div>
            <div className="total">
                {panier && panier.length > 0 ? (
                    <>
                        <div>Nombre de produits: {panier.length}</div>
                        <div>Total: {total} €</div>
                        <button onClick={viderPanier}>Vider le panier</button>
                    </>
                ) : (
                    <div>Votre panier est vide</div>
                )}
            </div>
        </div>
    );
    
};

export default Panier;
